import os
import sys
import traceback
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import yt_dlp

# 引入 ReportLab 用于安全生成 PDF
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from io import BytesIO

# 注册中文字体所需的 ReportLab 核心模块
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

app = Flask(__name__)

# 配置跨域，允许你的前端域名及本地调试环境
CORS(app, resources={r"/api/*": {
    "origins": ["https://www.rui-palace.com", "https://rui-palace.com", "http://127.0.0.1:5500", "http://localhost:5500"],
    "methods": ["POST", "OPTIONS"],
    "allow_headers": ["Content-Type"]
}})

# ==================== 🛠 字体注册逻辑 (FONT REGISTRATION) ====================
CHINESE_FONT_NAME = 'Helvetica'  # 默认安全回退字体

def register_chinese_font():
    """
    自适应加载你上传的 simsun.ttc 或 SourceHanSans-Regular.ttf。
    """
    global CHINESE_FONT_NAME
    
    # 1. 优先尝试加载宋体 (simsun.ttc)，兼容性最完美
    simsun_path = os.path.join(os.path.dirname(__file__), 'fonts', 'simsun.ttc')
    
    # 2. 备选尝试加载新下载的思源黑体 (SourceHanSans-Regular.ttf)
    shs_path = os.path.join(os.path.dirname(__file__), 'fonts', 'SourceHanSans-Regular.ttf')
    
    # 3. 垫底备份：Linux (Render) 系统内置中文字体路径
    system_font_path = "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc"
    
    try:
        if os.path.exists(simsun_path):
            # ttc 格式必须指定 subfontIndex=0 来读取“新宋体/宋体”
            pdfmetrics.registerFont(TTFont('ChineseFont', simsun_path, subfontIndex=0))
            CHINESE_FONT_NAME = 'ChineseFont'
            print("🎉 成功注册项目本地中文字体: 宋体 (simsun.ttc)")
            
        elif os.path.exists(shs_path):
            pdfmetrics.registerFont(TTFont('ChineseFont', shs_path))
            CHINESE_FONT_NAME = 'ChineseFont'
            print("🎉 成功注册项目本地中文字体: 思源黑体 (SourceHanSans-Regular.ttf)")
            
        elif os.path.exists(system_font_path):
            pdfmetrics.registerFont(TTFont('ChineseFont', system_font_path, subfontIndex=0))
            CHINESE_FONT_NAME = 'ChineseFont'
            print("🎉 成功注册 Linux 系统内置中文字体: 文泉驿微米黑")
            
        else:
            print("⚠️ 未在 fonts/ 目录下检测到有效字体，将回退至 Helvetica 渲染")
            
    except Exception as e:
        print(f"❌ 注册中文字体时发生错误: {str(e)}")
        print("⚠️ 自动回退到默认 Helvetica 渲染")

# 执行字体注册
register_chinese_font()
# ===========================================================================

def extract_playlist_info(playlist_url):
    """
    使用 yt-dlp 提取播放列表信息，此库更新极快，能有效绕过 YouTube 的反爬限制。
    """
    ydl_opts = {
        'extract_flat': True,
        'skip_download': True,
        'quiet': True
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        playlist_dict = ydl.extract_info(playlist_url, download=False)
        playlist_title = playlist_dict.get('title', 'YouTube Playlist')
        videos = []
        if 'entries' in playlist_dict:
            for entry in playlist_dict['entries']:
                if entry:
                    videos.append({
                        'title': entry.get('title', 'Unknown Title'),
                        'url': f"https://www.youtube.com/watch?v={entry.get('id')}" if entry.get('id') else playlist_url
                    })
        return playlist_title, videos

def generate_pdf_buffer(title, videos, lang='zh'):
    """
    在内存中生成包含中文且格式整齐的 PDF 报告。
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter,
        rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40
    )
    story = []
    styles = getSampleStyleSheet()
    
    # 动态应用已成功注册的字体
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName=CHINESE_FONT_NAME,
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#4A3E3D'),
        alignment=1
    )
    
    item_style = ParagraphStyle(
        'VideoItem',
        parent=styles['Normal'],
        fontName=CHINESE_FONT_NAME,
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#4A3E3D')
    )

    link_style = ParagraphStyle(
        'VideoLink',
        parent=styles['Normal'],
        fontName=CHINESE_FONT_NAME,
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#F4D1C6')
    )

    # 1. 标题
    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, 15))
    
    # 2. 元信息
    meta_text = f"Total Videos / 视频总数: {len(videos)} | Generated by Rui Palace"
    meta_style = ParagraphStyle(
        'Meta', 
        parent=styles['Normal'], 
        fontName=CHINESE_FONT_NAME, 
        fontSize=9, 
        textColor=colors.HexColor('#8C7A78'), 
        alignment=1
    )
    story.append(Paragraph(meta_text, meta_style))
    story.append(Spacer(1, 20))
    
    # 3. 视频表格数据构建
    table_data = []
    headers = ["#", "Video Title / 视频名称", "Interactive Link / 播放链接"]
    table_data.append([
        Paragraph(f"<b>{h}</b>", ParagraphStyle('H', parent=styles['Normal'], fontName=CHINESE_FONT_NAME, fontSize=9, textColor=colors.white)) 
        for h in headers
    ])
    
    for idx, video in enumerate(videos, 1):
        clean_video_title = clean_xml_char(video['title'])
        video_url = video['url']
        link_html = f'<a href="{video_url}" color="#E8BFA2"><u>Click to Play / 点击播放</u></a>'
        
        row = [
            Paragraph(str(idx), item_style),
            Paragraph(clean_video_title, item_style),
            Paragraph(link_html, link_style)
        ]
        table_data.append(row)
    
    col_widths = [30, 340, 160]
    video_table = Table(table_data, colWidths=col_widths)
    video_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4A3E3D')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#FDF6F0')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#F4D1C6')),
    ]))
    
    story.append(video_table)
    doc.build(story)
    buffer.seek(0)
    return buffer

def clean_xml_char(text):
    """
    过滤 XML 敏感控制字符，防止 ReportLab 的 XML 解析引擎抛出未捕获异常。
    """
    if not text:
        return ""
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

@app.route('/', methods=['GET', 'HEAD'])
def index():
    return jsonify({"status": "healthy", "service": "Rui Palace PDF API"}), 200

@app.route('/api/generate-pdf', methods=['POST'])
def generate_pdf():
    try:
        data = request.get_json()
        if not data:
            return jsonify({"error": "请求体不能为空"}), 400
        
        playlist_url = data.get('url')
        lang = data.get('lang', 'zh')
        
        if not playlist_url:
            return jsonify({"error": "未提供播放列表链接"}), 400
        
        # 1. 解析播放列表
        playlist_title, videos = extract_playlist_info(playlist_url)
        
        if not videos:
            return jsonify({"error": "未能解析到有效视频"}), 404
        
        # 2. 生成内存 PDF 缓冲
        pdf_buffer = generate_pdf_buffer(playlist_title, videos, lang)
        
        # 3. 安全返回文件流
        return send_file(
            pdf_buffer,
            mimetype='application/pdf',
            as_attachment=True,
            download_name=f"Playlist_Export.pdf"
        )
        
    except Exception as e:
        # 打印详细崩溃栈至 Render 控制台
        print("\n=== 💥 后端致命错误追踪 💥 ===")
        traceback.print_exc()
        print("=============================\n")
        return jsonify({
            "error": "服务器内部错误",
            "details": str(e)
        }), 500

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 10000))
    app.run(host='0.0.0.0', port=port)
